using System;
using System.IO;
using System.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoslynQuery.Query;

/// <summary>
/// Roslyn's own test (<c>GeneratedCodeUtilities</c>) is internal, so this reproduces the three
/// signals it uses - the file name, an auto-generated header comment, and <c>GeneratedCodeAttribute</c>
/// on every top-level type - plus a path test, which is what catches <c>obj\*.AssemblyInfo.cs</c>.
/// Split by cost: the name and path tests run before a document is opened, the rest need the tree.
/// </summary>
internal static class GeneratedCode
{
    private static readonly string[] Suffixes =
    {
        ".g.cs", ".g.i.cs", ".designer.cs", ".generated.cs", ".assemblyinfo.cs", ".assemblyattributes.cs"
    };

    public static bool IsGeneratedPath(Document document)
    {
        var name = document.Name ?? string.Empty;
        if (name.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase)) return true;

        foreach (var suffix in Suffixes)
            if (name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)) return true;

        return IsUnderIntermediateOutput(document.FilePath);
    }

    /// <summary>The signals that need the tree. Free wherever the root has already been parsed.</summary>
    public static bool IsGeneratedTree(SyntaxNode root) =>
        root != null && (HasAutoGeneratedHeader(root) || AllTypesAreGenerated(root));

    // The SDK writes AssemblyInfo, GlobalUsings and friends under obj\, and nothing a user wrote
    // belongs there. Compared per segment so a file merely named "objects.cs" is safe.
    private static bool IsUnderIntermediateOutput(string filePath)
    {
        if (string.IsNullOrEmpty(filePath)) return false;

        var directory = Path.GetDirectoryName(filePath);
        while (!string.IsNullOrEmpty(directory))
        {
            var segment = Path.GetFileName(directory);
            if (string.Equals(segment, "obj", StringComparison.OrdinalIgnoreCase)
                || string.Equals(segment, "bin", StringComparison.OrdinalIgnoreCase)) return true;

            directory = Path.GetDirectoryName(directory);
        }

        return false;
    }

    private static bool HasAutoGeneratedHeader(SyntaxNode root)
    {
        foreach (var trivia in root.GetLeadingTrivia())
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) && !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia)) continue;

            var text = trivia.ToString();
            if (text.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0) return true;
        }

        return false;
    }

    // Only top level: descending stops at the first type, so a generated outer type does not have
    // to carry the attribute on its nested ones. The Count check matters - "all of nothing" is
    // vacuously true, and an attribute-only file must fall through to the header test instead.
    private static bool AllTypesAreGenerated(SyntaxNode root)
    {
        var types = root
            .DescendantNodes(descendIntoChildren: node => node is CompilationUnitSyntax || node is BaseNamespaceDeclarationSyntax)
            .OfType<BaseTypeDeclarationSyntax>()
            .ToList();

        return types.Count > 0 && types.All(HasGeneratedCodeAttribute);
    }

    private static bool HasGeneratedCodeAttribute(BaseTypeDeclarationSyntax type) =>
        type.AttributeLists
            .SelectMany(list => list.Attributes)
            .Select(attribute => attribute.Name.ToString())
            .Any(name => name.EndsWith("GeneratedCode", StringComparison.Ordinal)
                || name.EndsWith("GeneratedCodeAttribute", StringComparison.Ordinal));
}
